// KEEP ALL TYPES IN A SINGLE FILE TO PREVENT CONFLICTS OF RE USING NAME 

// CLOCK MODULE TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'


